### ISSUE TITLE
Referencing glossary items from yaml or json file.

### ISSUE THREAD

**Issue by mholson** [swaits/typst-collection#1]
I am trying to assign my glossary stored in a yaml file; however, Typst is throwing an error when I compile.

When I run the following code, it shows that I can read the yaml file:
```typst
#import "@preview/glossy:0.1.1": *
#let myGlossary = yaml("mho-glossary.yaml")

//#show: init-glossary.with(myGlossary)

#myGlossary
```

It returns:
```yaml
(
html: (short: "REPL", long: "Hello"),
REPL: (short: "REPL", long: "Read"),
)
```

The problem is when I try running the following code as originally intended in my document:
```typst
#import "@preview/glossy:0.1.1": *
#let myGlossary = yaml("mho-glossary.yaml")

#show: init-glossary.with(myGlossary)

Hello @html World
```
Typst throws the following error

```shell
Typst Compilation started at Wed Oct 30 17:40:14

typst compile tech-gloss.typ 
error: expected integer, found string
   ┌─ @preview/glossy:0.1.1/src/gloss.typ:15:24
   │
15 │     let long = entry.at("long", default: none)
   │                         ^^^^^^

help: error occurred in this call of function `__normalize_entries`
    ┌─ @preview/glossy:0.1.1/src/gloss.typ:219:15
    │
219 │   for entry in __normalize_entries(entries) {
    │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Typst Compilation exited abnormally with code 1 at Wed Oct 30 17:40:18
```

Am I going about importing the yaml file correctly?  Similar error trying with a json file.

**Comment by swaits** [comment]
What does your YAML file look like? Something like this?

```yaml
- key: html
  short: HTML
  long: Hello

- key: repl
  short: REPL
  long: Read
```

The resulting `myGlossary` needs to be an array of dictionaries. Right now yours is a dictionary. In your example, you want it to look like:

```
(
  (
    key: "html",
    short: "HTML",
    long: "Hello",
  ),
  (
    key: "repl",
    short: "REPL",
    long: "Read",
  )
)
```

**Comment by swaits** [comment]
Please reopen if you have more issues. Thanks!

**Comment by mholson** [comment]
Thank you Stephen,@swaits!  It was indeed a problem with my yaml file structure.  I had been also playing around with **Glossarium** yesterday.  BTW, I really like how simple it is to call your package and implement it while using a dynamic project file structure - great work and thank you!  **Gloss** was exactly what I was looking to add to my notes workflow as I transition from _LaTeX_ to _Typst_.

**Comment by swaits** [comment]
Great to hear that. Thanks!
