### ISSUE TITLE
Glossy not finding Group in JSON File

### ISSUE THREAD

**Issue by Waldehyd** [swaits/typst-collection#10]
Hey, 

I have the following JSON File:

```
{
    "pbr": {
      "short": "PBR",
      "long": "Physically Based Rendering",
      "group": "abbreviation"
    }
  }
```
An the following code: 
```

#show: init-glossary.with(json("Glossaries/Abbreviations.json"))

#glossary(
  title: "Abbreviations",
  theme: my-theme,
  groups: ("abbreviation")
)

```
It get this error:

`panicked with: "Requested group not found: a"`

Am I missing something? Also, as a follow-up, is it possible to filter a Glossary by File instead of Group?

**Comment by swaits** [comment]
Might be a bug. I'll look into it.

**Comment by swaits** [comment]
Ok, so... this is a bit ugly. But update your code to this:

```typst
#glossary(
  groups: ("abbreviation",)
)
```

And it should work. This is to force your parameter into an array.

I'm going to probably change the interface in 0.2.3 so that it automatically detects this and handles your original approach. Regardless, this should at least get you up and running.

**Comment by Waldehyd** [comment]
Ah, I see, that works!
This leads my into another related error:
When i add another glossary file:
```
#show: init-glossary.with(json("Glossaries/Abbreviations.json"))
#show: init-glossary.with(json("Glossaries/Glossary.json"))
```
I get "panicked with: "Requested group not found: abbreviation"" because my second Glossary doesn't contain a group like that. I would expect it to just ignore the fact that this group doesn't exist?

**Comment by swaits** [comment]
Ahh yes. We only support one glossary file at this point.

You should be able to join the two dictionaries you're loading from json though. Something like this (note, untested):

```typst
#let dictionaries = json("Glossaries/Abbreviations.json") + json("Glossaries/Glossary.json")
#show: init-glossary.with(dictionaries)
```

Let me know if that works for you. If so, I'll close this.

**Comment by Waldehyd** [comment]
That does result in the same error, it doesn't seem to to addition although it's not complaining about that line either. Will see if i can find anything on appending JSONs.

My intended behavior seems to be impossible though. What I wanted is using one key, e.g. @pbr, and automatically add it to both Abbreviations (without description) in the front and in the Glossary (with description). But having the same key twice doesn't work out.

**Comment by swaits** [comment]
Ahh, yes, your use case is indeed impossible right now. The input to `init-glossary()` is a Typst `dictionary`. In that case, each key has to be unique. And thus, when you try to merge two dictionaries which share (any) common keys, you will have problems.

Maybe I can help you come up with a solution that gets you what you want? What is the end result you're really looking for here?

**Comment by Waldehyd** [comment]
I'll find in out! The thesis will take some years so maybe there will be changes in typst by then as well :D
Thanks for your time!
