### ISSUE TITLE
Glossy: Add article modifier for a/an

### ISSUE THREAD

**Issue by eltos** [swaits/typst-collection#12]
It would be great to have a modifier to allow the common handling of articles depending on short/long form.

For example:
- "a radio frequency (RF)" vs "an RF" (because the latter is spelled with a vowel sound: "ar-ef")
- "an untranslatable string (UTS)" vs "a UTS" (because the latter is spelled without a vowel sound: "ju-tee-ess")

Also, the combination with the `:cap` modifier to capitalize the A/An should be forseen.

## Suggestion 🅰

Add two modifiers `:a-an` and `:an-a` that add "a" or "an" in front of the word depending on first or subsequent usage like so:
  - `@rf:a-an` would get prefixed with "a " on first and "an " on subsequent usage
  - `@uts:an-a` would get prefixed with "an " on first and "a " on subsequent usage

Concise, but also limited.

## Suggestion 🅱
Add a single modifier `:a` to prepend the article if used as `@rf:a` or `@uts:a`. The default would be (for english):
- for short form: use "an" if short form starts with any of "AEFHILMNORSX", otherwise use "a"
- for long form: use "an" if long form starts with any of "aeiou", otherwise use "a"

In addition, the articles could be customized for the respective long/short form in the glossary dict:
```typ
#let glossary = (
  rf: (
    short: "RF",
    long: "radio frequency",
    articles: (short: "an", long: "a"),
  )
  uts: (
    short: "UTS",
    long: "untranslatable string",
    articles: (short: "a", long: "an"),
  )
)
```

Verbose but cleaner, and allows customization for other languages and edge cases too.

I think I prefer suggestion 🅱.
If you want help, I could submit a PR on this.

**Comment by swaits** [comment]
I also prefer suggestion **B**. It's the simpler user interface, which is always going to be my first choice.

I intentionally left articles out of `glossy` because I always found it was easy enough for me to just write them manually, like:

```
[
  an @rf:short
  a @rf:long
]
```

However, this implies I always know whether the short or long form will be used. So, I'm completely open to implementing this.

I like the suggestion and will work on implementation in the next few days.

**Comment by swaits** [comment]
Quick update. Created branch `issue-12`, and added a `__determine_article(word)` utility, with test. I'm pretty happy with this as a start.

Next up, to add support for the `:a` (and I think an alias `:an`) modifier to check the data, then default to this new function. Plus make sure `:cap` works as expected, and additionally panic when `:a`/`:an` is ever combined with `:pl`.

Changes here: https://github.com/swaits/typst-collection/compare/main...issue-12

**Comment by swaits** [comment]
Alrighty... I think I have this in decent shape. Ended up refactoring `__gls()` a good bit because it was a mess.

I'll let it bake here a bit before packaging it up into a release.

Diff again, if interested: https://github.com/swaits/typst-collection/compare/main...issue-12

**Comment by eltos** [comment]
Works like a charm, thanks a lot @swaits!

**Comment by swaits** [comment]
This is merged upstream. Should be live now.
