### ISSUE TITLE
`codly-languages.at("c")` returns entry for vimscript

### ISSUE THREAD

**Issue by Nevsor** [swaits/typst-collection#4]
```typst
#import "@preview/codly-languages:0.1.1": *

#codly-languages.at("c")
```

yields

![grafik](https://github.com/user-attachments/assets/cfd61c25-0fde-46ed-a2e8-04bed5ee82fb)

and

````typst
#import "@preview/codly:1.0.0": *
#show: codly-init.with()

#import "@preview/codly-languages:0.1.1": *
#codly(languages: codly-languages)

```c
int main() {}
```
````

yields

![grafik](https://github.com/user-attachments/assets/6875402e-0782-40eb-a3cc-c56eb38a43b5)

I am quite new to Typst and don't know how to investigate this issue. The file `lib.typ` (in the repo as well as the one downloaded by the import statement) looks good to me.

**Comment by swaits** [comment]
Strange. I'll take at look at this. Thanks for posting it.

**Comment by swaits** [comment]
Should be fixed by this: https://github.com/swaits/typst-collection/commit/0d84c91d6eb2ee0fb68ae45e41a1bc1f63774708

And will be live once this gets merged: https://github.com/typst/packages/pull/1356

Please reopen if that doesn't fix it for you.

**Comment by Nevsor** [comment]
Works great. Thank you!
