### ISSUE TITLE
Many aliases don't work

### ISSUE THREAD

**Issue by Nevsor** [swaits/typst-collection#5]
Many aliases defined in `lib.typ` are not present in `#codly-languages`.

This works:
```typst
#import "@preview/codly-languages:0.1.1": *
#codly-languages.at("cs")
```

This does not (`dictionary does not contain key "vimscript" and no default value was specified`):
```typst
#import "@preview/codly-languages:0.1.1": *
#codly-languages.at("vimscript")
```

**Comment by swaits** [comment]
Thanks for sharing. I'll look into this.

**Comment by swaits** [comment]
Should be fixed by this: https://github.com/swaits/typst-collection/commit/0d84c91d6eb2ee0fb68ae45e41a1bc1f63774708

And will be live once this gets merged: https://github.com/typst/packages/pull/1356

Please reopen if that doesn't fix it for you.
