### ISSUE TITLE
glossy case-sensitive alphabetical order

### ISSUE THREAD

**Issue by SarahKLinden** [swaits/typst-collection#7]
Really enjoying glossy, thanks for this. Noticed that generated glossaries are sorted case-sensitive, i.e. all terms beginning with upper case before all terms beginning with lower case. Is there a way to have case-insensitive sorting?

**Comment by swaits** [comment]
Glad you like it. 

I'll look into adding this as an option in the next few days.

**Comment by swaits** [comment]
Ok thanks for the suggestion. I added a parameter to `#glossary()` so you can do `#glossary(ignore-case: true)`.

Should be live once this PR merges: https://github.com/typst/packages/pull/1392

Please reopen if, once it's merged, it doesn't work for you.
